### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by nicolas-bastien** [impresspages/ImpressPagesBundle#1]
Hi, I work for a company specialized in Symfony2.

I saw the video on your site and I'm quite interested by your UI.

Can you tell me if you still plan to plug your CMS to symfony2 ?

Maybe I can test it and give you some help ?

**Comment by jankus** [comment]
If you can check how this bundle can be finished that would be awesome.

**Comment by maskas** [comment]
We had a community member who has started a Symfony bundle. As far as I remember current state lets you access ImpressPages functions from within Symfony. That's all it does at the moment.

**Comment by nicolas-bastien** [comment]
Ok thanks I'll give a try next week
